config:
  env: prod
  prod:
    db:
      host: 127.0.0.1
      dbname: odoo_dev_enterprise
      user: diego
      secret: DarkSide894518
    odoo:
      url: http://127.0.0.1:8069
      dbname: odoo_dev_enterprise
      user: diegomecatronico@gmail.com
      secret: DarkSide894518