config:
  env: prod
  prod:
    db:
      host: 192.168.99.56
      dbname: yellow_korner_db
      user: crusardi
      secret: cuB3bi8945*
    odoo:
      url: https://yellowkorner.odoo.com
      dbname: infotodoo-prueba-yk-master-535735
      user: admin
      secret: H26sEdCsnZ78Mbk